# Auto-generated locators from Business.xml

Object_SelectPayerFromAddressBook = "//button[@id='selectpayer']"
Object_SelectPayer = "//div[contains(text(),'${BusinessName}')]/parent::td/following-sibling::td/following-sibling::td/following-sibling::td/div/button"
Object_EditPayer = "//button[@id='editpayer']"
Object_ChangePayer = "//button[@id='changepayer']"
Object_AddNewPayer = "//*[@id='addnewpayer']"
Object_AddBusiness = "//button[@id='addbusiness']"
Object_CheckEIN = "//input[@aria-label='Employer Identification Number (EIN)']"
Object_CheckSSN = "//input[@aria-label='Social Security Number (SSN)']"
Object_PayerTIN = "//*[@id='textpayertin']"
Object_PayerReferenceNumber = "//input[@id='referencenumber']"
Object_BusinessName = "//*[@id='payernametextfield']"
Object_PayerFirstName = "//*[@id='payerfirstname']"
Object_PayerMiddleName = "//*[@id='payermiddlename']"
Object_PayerLastName = "//*[@id='payerlastname']"
Object_PayerSuffix = "//*[@id='payercontactsuffixlabel']/following-sibling::div"
Object_DBAorTradeName = "//*[@id='payertradename']"
Object_PayerCountryCode = "//*[@id='payercountrylabel']/following-sibling::div"
Object_PayerAddress1 = "//*[@id='payeraddressone']"
Object_PayerAddress2 = "//*[@id='payeraddresstwo']"
Object_Payercity = "//*[@id='payercityname']"
Object_PayerStateOrProvince = "//*[@id='payerstatelabel']/following-sibling::div"
Object_PayerZipOrPostalCode = "//*[@id='payerzipcode']"
Object_VerifyUSPSLink = "//a[@id='verifyaddresswithusps']"
Object_ValidAddressText = "//div[contains(text(),'Valid Address')]"
Object_Okay = "//div[contains(text(),'Valid Address')]/parent::div/parent::div/following-sibling::div/button"
Object_USPSRecomendedPopUpText = "//div[contains(text(),'USPS Recommended Address')]"
Object_AddressYouEntered = "//span[contains(text(),'Address you entered')]"
Object_USPSVerifiedAddress = "//span[contains(text(),'USPS Verified Address')]"
Object_USPSContinue = "//span[contains(text(),'Continue')]"
Object_USPSCancel = "//span[contains(text(),'Cancel')]"
Object_InvalidAddressText = "//div[contains(text(),'Invalid Address')]"
Object_IgnoreAndContinue = "//span[contains(text(),' Ignore and Continue')]"
Object_AddressValid = "//span[contains(text(),'Okay')]/parent::span/parent::button"
Object_AddressUSPSRecommended = "//span[contains(text(),'Continue')]/parent::span/parent::button"
Object_AddressIgnoreAndContinue = "//span[contains(text(),'Ignore and Continue')]/parent::span/parent::button"
Object_ContactFirstName = "//*[@id='payercontactfirstname']"
Object_ContactMiddleName = "//*[@id='payercontactmiddlename']"
Object_ContactLastName = "//*[@id='payercontactlastname']"
Object_ContactSuffix = "//*[@id='payercontactsuffixlabel']/following-sibling::div"
Object_EmailAddress = "//*[@id='EmailAddress1']"
Object_PhoneNumber = "//*[@id='PhoneNumber1']"
