Object_StartNewForm = "//div[@class='v-list-item__content']/div[text()=' Start New ']"
Object_AccountNumber = "//*[@id='AccountNumber']"
Object_FATCAFiling = "//*[@id='isfatcafilling']"
Object_SecondTINorNot = "//*[@id='issecondtinnot']"
Object_PayerCancel = "(//button[@id='cancel'])[2]"
Object_PayerSave = "//button[@id='save']"
Object_CloseButton = "(//i[@role='button'])[22]"
Object_RecipientCancel = "(//button[@id='cancel'])[2]"
Object_RecipientSave = "//button[@id='save']"
Object_SaveAndContinue1 = "//button[contains(@aria-label,'Save and Continue')]"
Object_SaveAndContinue2 = "//*[@id='saveandcontinue']"
Object_SaveAndAddAnother1 = "//button[@aria-label='Save & Add Another']"
Object_SaveAndAddAnother2 = "//button[@aria-label='Save and Add Another']"
Object_SaveAsDraft = "//button[@aria-label='Save for Later']"
Object_Cancel1 = "//button[@aria-label='Cancel']"
Object_Cancel2 = "//button[@aria-label='cancel']"
Object_Cancel3 = "//*[@id='cancel']"
Object_CancelPopupHeader = "//span[contains(text(),'Cancel Form')]"
Object_CancelPopupYes = "//button[@aria-label='yes']"
Object_CancelFilter = "//span[contains(@class,'TBS-filter-outline text-tertiary')]"
Object_DraftSuccessPage = "//th[contains(text(),'Last Updated On')]"
Object_ChangeForm = "//a[contains(text(),'Change Form')]"
Object_ChangeFormType = "//a[contains(text(),'Change Form')]"
Object_TotalForms="//h1[contains(text(),'Total Payers')]"
Object_AgreeAndProceed = "//span[text()=' Agree and Proceed ']/parent::button"
Object_OkayGotIt = "//span[text()=' Okay, Got It ']"
Object_State = "//input[@id='state']"
#Object_PayerStateNo = "//*[@id='payerstatenumber_1']"
Object_PayerStateNo = "//div[text()='Add Payer State Account Number ']/parent::div/following-sibling::div/div/div/div/input"
Object_StateIncome = "//*[@id='stateincometextfield_1']"
Object_StateTaxWithheld = "//*[@id='taxwidthheld_1']"
Object_FormRPayerState = "//input[@id='b13astate']"
Object_FormRStateTaxWithheld = "//input[@id='b12astatetaxwithheld']"
Object_FormRPayerStateNum = "//input[@id='b13astateidentificationno']"
Object_FormRStateDistribution = "//input[@id='b14astatedistribution']"
Object_FormRLocalTaxWithheld = "//input[@id='b15alocaltaxwithheld']"
Object_FormRNameOfLocality = "//input[@id='b16anameoflocality']"
Object_FormRLocalDistribution = "//input[@id='b17alocaldistribution']"
Object_FormGState = "//input[@id='state_1']"
Object_FormGStateNo = "//input[@id='payerstatenumber_1']"
Object_FormGStateTaxWithheld = "//input[@id='taxwidthheld_1']"
