# Auto-generated locators from HomeSite.xml

Object_NewFormClose = ""
Object_HomeDashboardStartFiling = "//span[text()='Go to Dashboard']/parent::button"
Object_W21099 = "//div[contains(text(),' Tax Form Filing ')]/parent::div/following-sibling::div/div/following-sibling::div/div/following-sibling::div/div/following-sibling::a[contains(text(),'1099/W-2')]"
Object_W21099Dashboard = "//div[contains(text(),'1099/W2')]/following-sibling::div/following-sibling::div/div/following-sibling::button"
Object_HomeSite94X = "//div[contains(text(),'Tax Form')]/parent::div/following-sibling::div/div[2]/div/div/a[contains(text(),'94x')]"
Object_HomeSite1099W2 = "//div[contains(text(),'Tax Form')]/parent::div/following-sibling::div/div[2]/div/div/a[contains(text(),'1099/W-2')]"
Object_HomeSite1042 = "//div[contains(text(),'Tax Form')]/parent::div/following-sibling::div/div[2]/div/div/a[contains(text(),'1042')]"
Object_HomeSiteACA = "//div[contains(text(),'Tax Form')]/parent::div/following-sibling::div/div[2]/div/div/a[contains(text(),'ACA')]"
Object_HomeSiteProFeaturesBanditCollab = "//button[@aria-label='Move to BanditCollab']"
Object_HomeSiteProFeaturesBanditConnect = "//button[@aria-label='Move to BanditConnect']"
Object_HomeSiteWhatsNew = "//span[text()=' See What�s New! ']/parent::a"
Object_HomeSiteBOIR = "//span[text()=' Start Reporting']/parent::button"
Object_HomeSitePayroll = "//span[text()=' Take A Quick Survey ']/parent::button"
Object_HomeSiteW9 = "//span[text()=' Share/Request W-9']/parent::button"
Object_StartNewForm = "//div[@class='v-list-item__content']/div[text()=' Start New ']"
Object_ChooseFormHeader = "//p[contains(text(),' Form 1099 Series ')]"
Object_ChooseCurrentTaxYear = "//button[@aria-label='start filing']"
Object_FormNEC = "//span[text()='1099-NEC ']/parent::button"
Object_FormMISC = "//span[text()='1099-MISC ']/parent::button"
Object_FormINT = "//span[text()='1099-INT ']/parent::button"
Object_FormDIV = "//span[text()='1099-DIV ']/parent::button"
Object_FormR = "//span[text()='1099-R ']/parent::button"
Object_FormS = "//span[text()='1099-S ']/parent::button"
Object_FormB = "//span[text()='1099-B ']/parent::button"
Object_FormK = "//span[text()='1099-K ']/parent::button"
Object_FormG = "//span[text()='1099-G ']/parent::button"
Object_FormC = "//span[text()='1099-C ']/parent::button"
Object_Form5498 = "//button[@aria-label='5498']/span[text()='5498']"
Object_Form5498SA = "(//span[text()='5498-SA']/parent::button)[2]"     
Object_Form5498ESA = "(//span[text()='5498-ESA']/parent::button)[2]"
Object_FormW2 = "(//button[@aria-label='W-2'])[1]"
Object_FormG = "//span[text()='1099-G ']/parent::button"
Object_FormOID = "//span[text()='1099-OID ']/parent::button"
Object_FormW2G = "//span[text()='W-2G ']/parent::button"
Object_FormLTC = "//span[text()='1099-LTC ']/parent::button"
Object_FormPATR = "//span[text()='1099-PATR ']/parent::button"
Object_FormQA = "//span[text()='1099-QA ']/parent::button"
Object_FormF = "//span[text()='1098-F ']/parent::button"
Object_Form1042S = "(//span[text()='1042-S']/parent::button)[1]"
Object_Form1098 = "//span[text()='1098 ']/parent::button"
Object_Form1098T = "//span[text()='1098-T ']/parent::button"
Object_FormE = "//span[text()='1098-E ']/parent::button"
Object_FormQ = "//span[text()='1099-Q ']/parent::button"
Object_FormA = "//span[text()='1099-A ']/parent::button"
Object_FormLTC = "//span[text()='1099-LTC ']/parent::button"
Object_Form3921 = "//span[text()='3921 ']/parent::button"
Object_Form3922 = "//span[text()='3922 ']/parent::button"
Object_FormSA = "//span[text()='1099-SA ']/parent::button"
