
Object_SitePassword="(//*[@id='Passwordfeild'])"
Object_SitePasswordContinue="//em[contains(text(),'Please enter the password to use the testing site')]/parent::p/following-sibling::div/button"
Object_Username="//*[@id='Email_Address_feild']"
Object_Password="//*[@id='Password_feild']"
Object_signin = "//button[@id='SignInbtn']"
Object_IlldoitLater = "//a[contains(text(),'do it later')]"
Object_Login="//span[text()=' Start New']"
Object_DashboardLogo="//div[@aria-label='Logo']"
Object_TwoFactorAuthenticationCode="//*[@id='verificationcodefield']"
Object_VerifyCode="//button[@aria-label='Verify the code']"
Object_ErrorMessageTwoFactor="//div[contains(text(),'Invalid Verification Code. 3 attempts until your account is temporarily locked.')]"
Object_ErrorResult="//div[contains(text(),'Error occured')]"
Object_Signup="//*[@id='SignupLink']"
Object_ForgetPasswordheader="//h1[contains(text(),'Forgot')]"
Object_ForgetPasswordEmailAddress="//*[@id='emailId']"
Object_ForgetPasswordContinue="//*[@id='ForgetPasswordContinue']"
Object_ForgetPasswordReturnToSignin="//*[@id='ReturnToSignIn']"
Object_ForgetPasswordCheckYourInbox="//h1[contains(text(),'Password Reset Link Sent – Check Your Inbox!')]"
Object_ForgetPasswordCheckYourInboxGoToSignin="//*[@id='GoToSignIn']"
Object_ForgetPassword="//a[contains(text(),'Forgot Password?')]"
Object_SignupHeader="//h1/span[contains(text(),'Sign Up')]"
Object_WorkEmail="//*[@id='WorkEmail']"
Object_ContactName="//*[@id='ContactName']"
Object_SignupPassword="//*[@id='Password']"
Object_PhoneNumber="//*[@id='PhoneNumber']"
Object_TaxPrefessional="//*[@id='IsTaxPreparer']"
Object_FirmName="//*[@id='FirmName']"
Object_HowManyClientsDoYouWorkWith="//*[@id='ifselfemployedlabel']/following-sibling::div"
Object_CreateAccount="//*[@id='createAccount']"
Object_OTAHeader="//span[contains(text(),'Verify your Email')]"
Object_OTA="//*[@id='otaverificationfeild']"
Object_Verify="//button[@aria-label='Vefify']"
Object_TwoFAHeader="//h1[contains(text(),'Enable Two-Factor Authentication (2FA)')]"
Object_TwoFAIWillDoItLater="//a[contains(text(),'do it Later')]"
Object_Welcome="//h1[contains(text(),'Welcome')]"
Object_WelcomeTagline="//h1[contains(text(),' Welcome Back ')]"
Object_GoToDashboard="//span[text()='Start ']/parent::button"
Object_DashBoardHeader="//p[contains(text(),'Welcome Back')]"
Object_ErrorOccured = "//*[contains(text(),'Error occured']"
