# Auto-generated locators from OrderHistory.xml

Object_ThreeDots = "//button[@aria-label='User Settings Menu']"
Object_NineDots = "//button[@aria-label='Control Panel']"
Object_AccountSettings = "//div[text()=' Account Settings ']"
Object_Payment = "//span[text()='Payment']"
Object_OrderHistory = "//div[text()=' Order History ']"
Object_RecieptView = "//button[@aria-label='Preview Receipt']"
Object_RecieptClose = "//div[@class='flex-grow-1']/following-sibling::i"
Object_RecieptDownload = "(//button[@aria-label='Download Receipt'])[1]"
Object_RecieptSearch = "//input[@placeholder='Search']"
Object_Period = "//input[@id='handlePeriodChange']"
Object_PeriodYesterday = "//span[text()='Yesterday']"
Object_PeriodThisWeek = "//span[text()='This Week']"
Object_PeriodLastWeek = "//span[text()='Last Week']"
Object_PeriodThisMonth = "//span[text()='This Month']"
Object_PeriodLastMonth = "//span[text()='Last Month']"
Object_PeriodCustom = "//span[text()='Custom']"
Object_FromDate = "//input[@id='FromDateStr']"
Object_ToDate = "//input[@id='ToDateStr']"
Object_SelectFromDate = "(//span[text()='1'])[2]"
Object_SelectToDate = "//span[text()='15']"
Object_GoButton = "//span[text()=' Go ']"
Object_OrderHistorySearch = "//input[@id='orderhistorysearchfield']"
