# Auto-generated locators from 5498.xml

Object_Form5498_IRAContributions = "//input[@id='b1iracontributions']"
Object_Form5498_RolloverContribution = "//input[@id='b2rollovercontributions']"
Object_Form5498_RothIRAConversionAmount = "//input[@id='b3rothiraamount']"
Object_Form5498_RecharacterizedContributions = "//input[@id='b4recharacteramount']"
Object_Form5498_FMVOfAccount = "//input[@id='b5fmvamount']"
Object_Form5498_LifeInsuranceCostIncludedInBox1 = "//input[@id='b6lifeinsurance']"
Object_Form5498_IRA = "//input[@id='b7isira']"
Object_Form5498_SEP = "//input[@id='b7issep']"
Object_Form5498_SIMPLE = "//input[@id='b7issimple']"
Object_Form5498_RothIRA = "//input[@id='b7isrothira']"
Object_Form5498_SEPContributions = "//input[@id='b8sepcontibutions']"
Object_Form5498_SIMPLEContributions = "//input[@id='b9simplecontributions']"
Object_Form5498_RothIRAContributions = "b10rothiracontributions"
Object_Form5498_CheckIfRMDFor2024 = "//input[@id='b11isrmd']"
Object_Form5498_RMDDate = "//input[@id='b12armddatestr']"
Object_Form5498_RMDAmount = "//input[@id='b12brmdamount']"
Object_Form5498_PostponedLateContrib = "//*[@id='b13apostponedamountfield']"
Object_Form5498_Year13b = "//input[@id='b13byear']"
Object_Form5498_Code13c = "//input[@id='b13ccode']"
Object_Form5498_Repayments = "//input[@id='b14arepayments']"
Object_Form5498_Code14b = "//input[@id='b14bcode']"
Object_Form5498_FMVOfCertainSpecifiedAssets = "//input[@id='b15afmvassets']"
Object_Form5498_Codes15b = "//input[@id='b15bcode']"
Object_Form5498_Codes15b2 = "//input[@id='b15bcode2']"
Object_Form5498_AccountNumber = "//input[@id='AccountNumber']"