# Auto-generated locators from B.xml

Object_FormB_Header = "//div[contains(text(),'Form 1099-B')]"
Object_FormB_AccountNumber = "//*[@id='Account']"
Object_FormB_CUSIPNumber = "//*[@id='CUSIP']"
Object_FormB_SecondTINNot = "//*[@id='TINnot']"
Object_FormB_FATCAFilingRequirement = "//*[@id='FATCA']"
Object_FormB_ApplicableCheckboxOnForm8949 = "//*[@id='Applicable']"
Object_FormB_ApplicableCheckboxA = "//input[contains(@aria-label,'(A) Short-term transactions reported on Forms 1099-B showing basis was reported to the IRS')]"
Object_FormB_ApplicableCheckboxB = "//input[contains(@aria-label,'(B) Short-term transactions reported on Forms 1099-B showing basis wasn')]"
Object_FormB_ApplicableCheckboxD = "//input[contains(@aria-label,'(D) Long-term transactions reported on Forms 1099-B showing basis was reported to the IRS')]"
Object_FormB_ApplicableCheckboxE = "//input[contains(@aria-label,'(E) Long-term transactions reported on Forms 1099-B showing basis was')]"
Object_FormB_ApplicableCheckboxX = "//input[contains(@aria-label,'(X) Cannot determine whether the recipient should check Box B or Box E on Form 8949 because the holding period is unknown')]"
Object_FormB_ApplicableContinue = "//button[@aria-label='close popup']/span[text()='Continue ']/parent::button"
Object_FormB_DescriptionOfProperty = "//*[@id='Description']"
Object_FormB_DateAcquired = "//*[@id='b12armddatestr']"
Object_FormB_DateSoldOrDisposed = "//*[@id='B1cSoldDate']"
Object_FormB_Proceeds = "//*[@id='Proceeds']"
Object_FormB_CostOrOtherBasis = "//*[@id='Cost']"
Object_FormB_AccuredMarketDiscount = "//*[@id='Accrued']"
Object_FormB_WashSaleLossDisallowed = "//*[@id='Wash']"
Object_FormB_ShortTermGainOrLoss = "//*[@id='Short']"
Object_FormB_LongTermGainOrLoss = "//*[@id='Long-term']"
Object_FormB_Ordinary = "//*[@id='Ordinary']"
Object_FormB_Collectibles = "//*[@id='Collectibles']"
Object_FormB_QOF = "//*[@id='QOF']"
Object_FormB_FederalIncomeTaxWithheld = "//*[@id='Federal']"
Object_FormB_CheckIfNonRecoveredSecurity = "//*[@id='noncovered']"
Object_FormB_ReportedToIRSGrossProceeds = "//*[@id='Gross']"
Object_FormB_ReportedToIRSNetProceeds = "//*[@id='Net']"
Object_FormB_CheckIfLossIsNotAllowedBasedOnAmountIn1d = "//*[@id='allowed']"
Object_FormB_ProfitOrLossRealisedIn2023OnClosedContracts = "//*[@id='Profit']"
Object_FormB_UnrealisedProfitOrLossOnOpenContracts12312022 = "//*[@id='Unrealized']"
Object_FormB_UnrealizedProfitOrLossOnOpenContracts12312023 = "//*[@id='contracts']"
Object_FormB_AggregateProfitOrLossOnContracts = "//*[@id='Aggregate']"
Object_FormB_CheckIfBasisReportedToIRS = "//*[@id='basis']"
Object_FormB_Bartering = "//*[@id='Bartering']"
