# Auto-generated locators from R.xml

Object_FormR_GrossDistribution = "//input[@id='b1grossdistribution']"
Object_FormR_TaxableAmount = "//input[@id='b2ataxableamount']"
Object_FormR_TaxableAmountNotDetermined = "//input[@id='B2bistaxableamtnotdetermined']"
Object_FormR_TotalDistribution = "//input[@id='b2bistotaldistribution']"
Object_FormR_CapitalGain = "//input[@id='b3capitalgain']"
Object_FormR_FederalIncomeTaxWithheld = "//input[@id='b4federalincometaxwithheld']"
Object_FormR_EmployeeContributionsDesignatedRothContributionsOrInsurancePremiums = "//input[@id='b5employeecontribution']"
Object_FormR_NetUnrealizedAppreciationInEmployersSecurities = "//input[@id='b6netunrealizedappreciation']"
Object_FormR_DistributionCode1 = "//input[@id='b7distributioncode1']/parent::div"
Object_FormR_DistributionCode2 = "//input[@id='b7distributioncode2']/parent::div"
Object_FormR_IRASEPSIMPLE = "//input[@id='b7isIRAsimple']"
Object_FormR_Others = "//input[@id='b8otheramount']"
Object_FormR_OtherPercent = "//input[@id='b8otherpercent']"
Object_FormR_YourPercentageOfTotalDistribution = "//input[@id='b9atotaldistributionpercentage']"
Object_FormR_TotalEmployeeContributions = "//input[@id='b9btotalemployeedistribution']"
Object_FormR_AmountAllocableToIRRWithin5Years = "//input[@id='b10amountallocableToirr']"
Object_FormR_FirstYearOfDesigRothContrib = "//input[@id='b11yeardesignroth']"
Object_FormR_FATCAFilingRequirement = "//input[@id='isfactafiling']"
Object_FormR_DateOfPayment = "//input[@id='b12armddatestr']"
Object_FormR_AccountNumber = "//*[@id='accountnumber']"
