Object_FormF_AccountNumber="//*[@id='accountfeild']"
Object_FormF_TotalAmountRequiredToBePaid="//*[@id='Box1RequiredAmountfeild']"
Object_FormF_AmountToBePaidForViolationOrPotentialViolation="//*[@id='Box2ViolationAmountfeild']"
Object_FormF_RestitutionRemediationAmount="//*[@id='Box3RemediationAmountfeild']"
Object_FormF_ComplianceAmount="//*[@id='Box4ComplianceAmountfeild']"
Object_FormF_DateOfOrderAgreement="//*[@id='b12armddatestr']"
Object_FormF_CourtOrEntity="//*[@id='Box6Courtfeild']"
Object_FormF_CaseNumber="//*[@id='Box7CaseNumberfeild']"
Object_FormF_CaseNameOrNamesOfPartiesToSuitOrderOrAgreement="//*[@id='Box8CaseNamefeild']"
Object_FormF_Code_A="//*[@id='Box9Code1lable']"
Object_FormF_Code_B="//*[@id='Box9Code2lable']"
Object_FormF_Code_C="//*[@id='Box9Code3lable']"
Object_FormF_Code_D="//*[@id='Box9Code4lable']"
Object_FormF_Code_E="//input[@aria-label='E—Payment amount not identified']"

