# Auto-generated locators from K.xml

Object_FormK_Header = "//div[contains(text(),'Form 1099-B')]"
Object_FormK_AccountNumber = "//*[@id='Account']"
Object_FormK_PaymentSettlementEntity = "//*[@id='Paymentcheck']"
Object_FormK_ElectronicPaymentFacilitator = "//*[@id='Electroniccheck']"
Object_FormK_PaymentCard = "//*[@id='Paymentcardcheck']"
Object_FormK_ThirdPartyNetwork = "//*[@id='Thirdcardcheck']"
Object_FormK_PSEName = "//*[@id='pselablefeild']"
Object_FormK_NameCont = "//*[@id='namecontfeild']"
Object_FormK_PSEPhoneNumber = "//*[@id='phonenumberfeild1']"
Object_FormK_FormKAccountNumber = "//*[@id='Account']"
Object_FormK_SecondTINNot = "//*[@id='TINnot']"
Object_FormK_GrossAmountOfPaymentCardThirdPartyNetworkTransactions = "//*[@id='Gross']"
Object_FormK_CardNotPresentTransactions = "//*[@id='Card']"
Object_FormK_MerchantCategoryCode = "//*[@id='Merchantfeild']"
Object_FormK_MerchantCategoryCodeChooseCodes = "//*[@id='Merchant']/a"
Object_FormK_MerchantCategoryCodeChooseCodesHeader = "//div[contains(text(),'Choose Merchant Category Code')]"
Object_FormK_MerchantCategoryCodeVeterinaryServices = "//div[contains(text(),'Veterinary services')]/parent::td/following-sibling::td/div/button"
Object_FormK_NumberOfPaymentTransactions = "//*[@id='transactions']"
Object_FormK_FederalIncomeTaxWithheld = "//*[@id='Federal']"
Object_FormK_January = "//*[@id='January']"
Object_FormK_February = "//*[@id='February']"
Object_FormK_March = "//*[@id='March']"
Object_FormK_April = "//*[@id='April']"
Object_FormK_May = "//*[@id='May']"
Object_FormK_June = "//*[@id='June']"
Object_FormK_July = "//*[@id='July']"
Object_FormK_August = "//*[@id='August']"
Object_FormK_September = "//*[@id='September']"
Object_FormK_October = "//*[@id='October']"
Object_FormK_November = "//*[@id='November']"
Object_FormK_December = "//*[@id='December']"
