# Auto-generated locators from W2G.xml

Object_FormW2G_ReportableWinnings = "//input[@id='reportablewinnings']"
Object_FormW2G_DateWon = "//input[@id='datewonstr']"
Object_FormW2G_TypeOfWager = "//input[@id='typeofwager']/parent::div"
Object_FormW2G_FederalIncomeTaxWithheld = "//input[@id='federalincometaxwithheld']"
Object_FormW2G_Transaction = "//input[@id='b5transaction']"
Object_FormW2G_Race = "//input[@id='race']"
Object_FormW2G_WinningsFromIdenticalWagers = "//input[@id='winningsfromidenticalwagers']"
Object_FormW2G_Cashier = "//input[@id='cashier']"
Object_FormW2G_Window = "//input[@id='window']"
Object_FormW2G_FirstIdentification = "//input[@id='firstidentification']"
Object_FormW2G_SecondIdentification = "//input[@id='secondidentification']"
Object_FormW2G_State = "//input[@id='state1code']"
Object_FormW2G_StateIdNumber = "//input[@id='state1idnumber']"
Object_FormW2G_StateWinnings = "//input[@id='state1wages']"
Object_FormW2G_StateTaxWithheld = "//input[@id='state1withheld']"
Object_FormW2G_LocalWinnings = "//input[@id='local1wages']"
Object_FormW2G_LocalIncomeTaxWithheld = "//input[@id='local1withheld']"
Object_FormW2G_NameOfLocality = "//input[@id='local1name']"