# Auto-generated locators from DIV.xml

Object_FormDIV_TotalOrdinaryDividends = "//*[@id='ordinary']"
Object_FormDIV_QualifiedDividends = "//*[@id='Qualified']"
Object_FormDIV_TotalCapitalGainDistr = "//*[@id='capital']"
Object_FormDIV_UnrecapSec1250Gain = "//*[@id='Unrecap']"
Object_FormDIV_Section1202Gain = "//*[@id='B2cSection1202Gain']"
Object_FormDIV_Collectibles28Gain = "//*[@id='Collectibles']"
Object_FormDIV_Section897OrdinaryDividends = "//*[@id='Section897']"
Object_FormDIV_Section897CapitalGain = "//*[@id='Section897capital']"
Object_FormDIV_NondividendDistributions = "//*[@id='B3nonDividendsDistributions']"
Object_FormDIV_FederalIncomeTaxWithheld = "//*[@id='B4FederalIncometaxWithheld']"
Object_FormDIV_Section199Adividends = "//*[@id='B5Section199ADividends']"
Object_FormDIV_InvestmentExpenses = "//*[@id='B5InvestmentExpenses']"
Object_FormDIV_ForeignTaxPaid = "//*[@id='B6ForeignTaxpaid']"
Object_FormDIV_ForeignCountryOrUSPossession = "//*[@id='B7ForeignOrUS']"
Object_FormDIV_CashLiquidationDistributions = "//*[@id='B8CashLiquidationDistribution']"
Object_FormDIV_NoncashLiquidationDistributions = "//*[@id='Noncashliquidation']"
Object_FormDIV_ExecmptInterestDividends = "//*[@id='B10ExemptIntrestDividends']"
Object_FormDIV_SpecifiedPrivateActivityBondInterestDividends = "//*[@id='B11SPABondIntrestDividends']"
Object_FormDIV_AccountNumber=  "//*[@id='accountnumber']"
