# Auto-generated locators from LTC.xml

Object_FormLTC_GrossLongTermCareBenefitsPaid = "//*[@id='Grosslable']"
Object_FormLTC_AcceleratedDeathBenefitsPaid = "//*[@id='Accelerated']"
Object_FormLTC_CheckIfApplicablePerDiem = "//*[@id='Perdiem']"
Object_FormLTC_CheckIfApplicableReimbursedAmount = "//*[@id='Reimbursed']"
Object_FormLTC_InsuredSSN = "//*[@id='ssn']"
Object_FormLTC_InsuredATIN = "//label[@for='ATIN']"
Object_FormLTC_InsuredITIN = "//label[@for='ITIN']"
Object_FormLTC_TIN = "//*[@id='insuredtin']"
Object_FormLTC_FirstName = "//*[@id='payerfirstname']"
Object_FormLTC_MiddleInitial = "//*[@id='payermiddlename']"
Object_FormLTC_LastName = "//*[@id='payerlastname']"
Object_FormLTC_Suffix = "//*[@id='payersuffix']"
Object_FormLTC_Country = "//*[@id='InsuredsCountryCodelable']"
Object_FormLTC_AddressLine1 = "//*[@id='InsuredsStreetAddress']"
Object_FormLTC_AddressLine2 = "//*[@id='InsuredsStreetAddress2']"
Object_FormLTC_CityOrTown = "//*[@id='InsuredsCity']"
Object_FormLTC_State = "//*[@id='InsuredsForeignAddress']"
Object_FormLTC_ZIPCode = "//*[@id='zipcode']"
Object_FormLTC_QualifiedContract = "//*[@id='Qualifiedfeild']"
Object_FormLTC_ChronicallyIll = "//*[@id='B5IsChronicallyIll']"
Object_FormLTC_TerminallyIll = "//*[@id='Terminally']"
Object_FormLTC_DateCertified = "//*[@id='b12armddatestr']"
Object_FormLTC_AccountNumber = "//*[@id='Account']"
