# Auto-generated locators from MISC.xml

Object_FormMISC_Add = "//i[@class='v-icon notranslate mdi mdi-plus theme--dark']"
Object_FormMISC_Form = "//i[@class='v-icon notranslate mdi mdi-close theme--dark']/parent::span/parent::button/following-sibling::div/div/div/div[1]/div/div/div[contains(text(),'Form')]/parent::div"
Object_FormMISC_MISC = "(//span[contains(text(),'1099-MISC')])"
Object_FormMISC_Rents = "//input[@id='B1Rents']"
Object_FormMISC_Royalties = "//input[@id='b2royalties']"
Object_FormMISC_OtherIncome = "//input[@id='b3otherincome']"
Object_FormMISC_FederaIlncomeTaxWithheld = "//input[@id='b4fitwithheld']"
Object_FormMISC_FishingBoatProceeds = "//input[@id='b5fishingboat']"
Object_FormMISC_MedicalAndHealthCarePayments = "//input[@id='b6medicalandhealth']"
Object_FormMISC_PayerMadeDirectSales = "//input[@id='b7isdirectsale']"
Object_FormMISC_SubstitutePaymentsInLieuOfDividendsOrInterest = "//input[@id='b8substitutepayments']"
Object_FormMISC_CropInsuranceProceeds = "//input[@id='b9cropinsurance']"
Object_FormMISC_GrossProceedsPaidToAnAttorney = "//input[@id='b10grossproceeds']"
Object_FormMISC_FishPurchasedForReSale = "//input[@id='b11fishpurchasedforresale']"
Object_FormMISC_Section409ADeferrals = "//input[@id='b12sec409adeferrals']"
Object_FormMISC_ExcessGoldenParachutePayments = "//*[@id='isfatcafilling']"
Object_FormMISC_NonqualifiedDeferredCompensation = "//*[@id='b14nonqualdefComp']"
Object_FormMISC_AccountNumber=  "//*[@id='AccountNumber']"