# Auto-generated locators from BulkUploadTemplate.xml

Object_BulkUploadTemplates = "//div[contains(text(),'Bulk Upload Templates')]"
Object_DownloadTemplate = "//div[contains(text(),'Download Template')]"
Object_Instructions = "//div[contains(text(),'Instructions')]"
Object_CSVInstructionsHeader = "//div[contains(text(),'CSV Instructions')]"
Object_CSVDownload = "//span[text()=' Download ']/parent::button"
Object_CSVOkay = "//button[@aria-label='okay']"
Object_CSVClose = "//div[contains(text(),'CSV Instructions')]/following-sibling::button"
Object_General = "//button[@value='general']"
Object_TBS1099W2 = "//button[@value='1099/W-2']"
Object_Form94XSeries = "//button[@value='94x']"
Object_ACASeries = "//button[@value='ACA']"
Object_PayerBulkUpload = "//div[contains(text(),'Payer Bulk Upload')]/following-sibling::div/button"
Object_RecipientBulkUpload = "//div[contains(text(),'Recipient Bulk Upload')]/following-sibling::div/button"
Object_TeamMembersBulkUpload = "//div[contains(text(),'Team Members Bulk Upload')]/following-sibling::div/button"
Object_FormW2RecipientsOnly = "//div[contains(text(),'Form W2')]/following-sibling::div/div/div[contains(text(),'Recipients Only')]/following-sibling::div/button"
Object_FormINTPayersAndRecipients = "//div[contains(text(),'Form 1099-INT')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormSPayersAndRecipients = "//div[contains(text(),'Form 1099-S')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormCPayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormDIVPayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormBPayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_Form1098PayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormRPayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormGPayersAndRecipients = "//div[contains(text(),'Form 1099-C')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormNECRecipientsOnly = "//div[contains(text(),'Form 1099-NEC')]/following-sibling::div/div/div[contains(text(),'Recipients Only')]/following-sibling::div/button"
Object_FormNECPayerAndRecipients = "//div[contains(text(),'Form 1099-NEC')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormOIDRecipientsOnly = "//div[contains(text(),'Form 1099-OID')]/following-sibling::div/div/div[contains(text(),'Recipients Only')]/following-sibling::div/button"
Object_FormOIDPayerAndRecipients = "//div[contains(text(),'Form 1099-OID')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_FormMISCRecipientsOnly = "//div[contains(text(),'Form 1099-MISC')]/following-sibling::div/div/div[contains(text(),'Recipients Only')]/following-sibling::div/button"
Object_FormMISCPayerAndRecipients = "//div[contains(text(),'Form 1099-MISC')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_Form1098TRecipientsOnly = "//div[contains(text(),'Form 1098-T')]/following-sibling::div/div/div[contains(text(),'Recipients Only')]/following-sibling::div/button"
Object_Form1098TPayerAndRecipients = "//div[contains(text(),'Form 1098-T')]/following-sibling::div/div/div[contains(text(),'Payers')][contains(text(),'Recipients')]/following-sibling::div/button"
Object_Form941Q1Template = "//div[contains(text(),'Form 941 Q1 Template')]/following-sibling::div/button"
Object_Form941Q2Template = "//div[contains(text(),'Form 941 Q2 Template')]/following-sibling::div/button"
Object_Form941Q3Template = "//div[contains(text(),'Form 941 Q3 Template')]/following-sibling::div/button"
Object_Form941Q4Template = "//div[contains(text(),'Form 941 Q4 Template')]/following-sibling::div/button"
Object_Form941ScheduleRQ1Template = "//div[contains(text(),'Form 941 Schedule R Q1 Template')]/following-sibling::div/button"
Object_Form941ScheduleRQ2Template = "//div[contains(text(),'Form 941 Schedule R Q2 Template')]/following-sibling::div/button"
Object_Form941ScheduleRQ3Template = "//div[contains(text(),'Form 941 Schedule R Q3 Template')]/following-sibling::div/button"
Object_Form941ScheduleRQ4Template = "//div[contains(text(),'Form 941 Schedule R Q4 Template')]/following-sibling::div/button"
Object_Form940Template = "//div[contains(text(),'Form 940 Template')]/following-sibling::div/button"
Object_Form940ScheduleRTemplate = "//div[contains(text(),'Form 940 Schedule R Template')]/following-sibling::div/button"
Object_Form1095-BTemplate = "//div[contains(text(),'Form 1095-B Template')]/following-sibling::div/button"
Object_Form1095-CTemplate = "//div[contains(text(),'Form 1095-C Template')]/following-sibling::div/button"
Object_FormMA1099-HCTemplate = "//div[contains(text(),'Form MA 1099-HC Template')]/following-sibling::div/button"
