# Auto-generated locators from Groups.xml

Object_ThreeDots = "//button[@aria-label='User Settings Menu']"
Object_NineDots = "//button[@aria-label='Control Panel']"
Object_ManageGroups = "//div[text()='Manage Groups']"
Object_CreatGroup = "//span[text()=' Create Group ']"
Object_CloseGroup = "//button[@aria-label='Close pop up']"
Object_Cancel = "//*[text()=' Cancel ']"
Object_GroupName = "//input[@id='GroupName']"
Object_GroupDescription = "//textarea[@id='GroupDescription']"
Object_CreateGroup = "//span[text()='Create Group ']"
Object_More = "//button[@aria-label='More'][1]"
Object_Delete = "//div[text()=' Delete ']"
Object_DeletePopUPClose = "//button[@aria-label='close pop up']"
Object_DeletePopUpNo = "//button[@aria-label='No']"
Object_DeletePopUpYes = "//button[@aria-label='yes']"
Object_SelectGroup = "//input[@id='managegroupSelect_0']"
Object_BulkAction = "//button[@aria-label='Bulk Action']"
Object_AssignTeamMembers = "//div[text()='Assign Team Members']"
Object_AssignPayers = "//div[text()='Assign Payers`']"
Object_Search = "//input[@aria-labelledby='searchlable']"
Object_AssignTeamMemberClose = "//button[@aria-label='Close pop up']"
Object_AssignTeamMemberCancel = "//*[text()=' Cancel ']"
Object_Select = "//input[@id='Selectallheader']"
Object_AssignTeammember = "//span[text()=' Assign Team Member ']"
Object_AssignPayer = "Assign Payers"
Object_AddPayerClose = "//button[@aria-label='Close pop up']"
Object_AddPayerCancel = "//*[text()=' Cancel ']"
Object_SelectPayer = "//input[@id='Selectallheader']"
Object_AssignNewPayerButton = "//span[text()=' Assign New Payer ']"
Object_AddedPayersAddPayer = "//*[text()='Add Payer']"
Object_SelectAddPayer = "//input[@id='Selectallheader']"
Object_AssignNewPayer = "//button[@aria-label='Assgin New Payer']"
Object_AssignedTeamMembers = "//*[text()='Assign Team Members']"
Object_AssignTeamMemberSelect = "//input[@id='Selectallheader']"
Object_AssignTeamMemberButton = "//span[text()=' Assign Team Member ']"
Object_ManageGroupSearch = "//input[@placeholder='Search']"
Object_SearchGroupName = "//input[@placeholder='Enter Group Name']"
Object_Filter = "//span[text()='Filter']"
Object_FilterSearch = "//input[@id='Searchby']"
Object_FilterTeamMember = "//div[text()='Team Members']"
Object_FilterTeamMemberSearch = "//input[@placeholder='Search by Team Member']"
