# Auto-generated locators from Recipient.xml

Object_SelectRecipientFromAddressBook = "//button[@id='selectrecipient']"
Object_AddNewRecipient = "//*[@id='addnewrecipient']"
Object_AddRecipient = "//button[@id='addrecipient']"
Object_EditRecipient = "//button[@id='editrecipient']"
Object_ChangeRecipient = "//button[@id='changerecipient']"
Object_RecipientEIN = "//label[@for='ein']"
Object_RecipientSSN = "//label[@for='ssn']"
Object_Other = "//label[contains(text(),'Other')]"
Object_TinNotProvided = "//input[@id='tinnotprovided']"
Object_RecipientSelectOtherTINType = "//input[@id='other']"
Object_RecipientTIN = "//*[@id='tin']"
Object_RecipientName = "//*[@id='name']"
Object_RecipientDBAorTradeName = "//*[@id='dbaname']"
Object_RecipientFirstName = "//input[@id='firstname']"
Object_RecipientMiddleName = "//input[@id='middlename']"
Object_RecipientLastName = "//input[@id='lastname']"
Object_RecipientSuffix = "//input[@id='suffix']"
Object_RecipientCountryCode = "//input[@id='countrycode']"
Object_RecipientAddress1 = "//input[@id='address1']"
Object_RecipientAddress2 = "//input[@id='address2']"
Object_RecipientCity = "//input[@id='city']"
Object_RecipientStateOrProvince = "//input[@id='statecode']"
Object_RecpientZipOrPostalCode = "//input[@id='zipcode']"
Object_RecipientEmailAddress = "//input[@id='emailaddress']"
Object_RecipientPhoneNumber = "//input[@id='telephoneno']"
