# Auto-generated locators from ReDirection.xml

Object_ThreeDots = "//button[@aria-label='User Settings Menu']"
Object_NineDotsManual = "(//*[@id='control-panel-button'])[1]"
Object_NineDotsAuto = "(//*[@id='control-panel-button'])[2]"
Object_Credits = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Credits')]"
Object_BanditCollab = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'BanditCollab')]"
Object_ActivityLog = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Activity Log')]"
Object_AccountSettings = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Account Settings')]"
Object_FullServiceUpload = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Full Service Upload')]"
Object_OrderHistory = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Order History')]"
Object_BulkUploadTemplates = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Bulk Upload Templates')]"
Object_Reports = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[2][contains(text(),'Reports')]"
Object_Dashboard1099W2 = "//*[@id='1099W2Dashboard']"
Object_Dashboard94X = "//button[@aria-label='94X Dashboard']"
Object_DashboardACA = "//h1[contains(text(),'Dashboard')]/parent::div/parent::div/following-sibling::div[1]/div[4]/div/div[4]/button[@aria-label='ACA Dashboard']"
Object_CollapseMenu = "(//button[@aria-label='Collapse Menu'])[2]"
Object_Menu1099W2 = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='1099/W-2 Dashboard']"
Object_Menu94X = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='94x Dashboard']"
Object_Menu1042 = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='1042 Dashboard']"
Object_MenuACA = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='ACA Dashboard']"
Object_MenuDistributionCenter = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='Distribution Center New']"
Object_MenuAddressBook = "(//div[@aria-label='Menu List'])[2]/div/div/button[@aria-label='Address Book']"
Object_MenuBOIR = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[contains(text(),'BOIR')]/parent::div"
Object_Menuw9 = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[contains(text(),'W-9/W-8BEN')]/parent::div"
Object_MenuEFTPS = "//div[@aria-labelledby='control-panel-button']/div/div/div/div/div[contains(text(),'EFTPS')]/parent::div"
Object_MenuMoreForms = "//button[@aria-label='Product Menu']"
Object_Menu1099W2Auto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='1099/W-2 Dashboard']"
Object_Menu94XAuto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='94x Dashboard']"
Object_Menu1042Auto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='1042 Dashboard']"
Object_MenuACAAuto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='ACA CollapseMenu']"
Object_MenuDistributionCenterAuto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='Distribution Center New']"
Object_MenuAddressBookAuto = "(//div[@aria-label='Menu List'])[1]/div/div/button[@aria-label='Address Book']"
Object_MenuBOIRAuto = "//span[contains(text(),'BOI Reporting')]/preceding-sibling::span"
Object_Menuw9Auto = "//span[contains(text(),'W9/W8 BEN')]/preceding-sibling::span"
Object_MenuwEFTPSAuto = "//span[contains(text(),'EFTPS')]/preceding-sibling::span"
Object_MenuwTINMatchingAuto = "//span[contains(text(),'TIN Matching')]/preceding-sibling::span"
Object_MenuwRetirementBenefitsAuto = "//span[contains(text(),'Retirement Benefits')]/preceding-sibling::span"
Object_Profile = "//button[@aria-label='View Profile']"
Object_ProfileAuto = "(//button[@aria-label='View Profile'])[2]"
Object_ProfileYourProfile = "//div[@role='listbox']/div/div[2]/div[contains(text(),'Your Profile')]"
Object_ProfilePassword = "//div[@role='listbox']/div/div[2]/div[contains(text(),'Password')]"
Object_ProfileTwoFactorAuthentication = "//div[@role='listbox']/div/div[2]/div[contains(text(),'Two-Factor Authentication')]"
Object_ProfileSupportCenter = "//div[@role='listbox']/a/div[2]/div[contains(text(),'Support Center')]"
Object_ProfileAccountSettings = "//div[@role='listbox']/div/div[2]/div[contains(text(),'Account Settings')]"
Object_FooterTermsOfUse = "//a[contains(text(),'Terms of Use')]"
Object_FooterPrivacyPolicy = "//a[contains(text(),'Privacy Policy')]"
Object_FooterFeedback = "//a[contains(text(),'Feedback')]"
Object_FooterRecommendUs = "//a[contains(text(),'Recommend Us')]"
Object_FooterSiteAccessibility = "//a[contains(text(),'Site Accessibility')]"
Object_FooterHelp = "//a[contains(text(),'Help')]"
