
# Auto-generated locators from ReviewReturnPage.xml
Object_FederalFilingHeader = "//*[@id='FederalTab']"
Object_ViewBusiness = "//*[@id='ViewBusiness']"
Object_ViewBusinessclose = "//span[text()='Cancel']/parent::button[@aria-label='close']"
#Object_TIN1 = "//span[@aria-label='hide password']/parent::div"
Object_TIN1 = "//button[@aria-label='mask/unmask']/parent::div"     
Object_TIN2 = "//span[@aria-label='hide password']/parent::span/parent::button/parent::div"
Object_ContinueToStateFiling = "//*[@id='ContinueToState']"
Object_Federal_ReturnDelete = "//button[@aria-label='Open share form']"
Object_Federal_ReturnDeleteYes = "//button[@aria-label='yes']"
Object_Federal_ReturnDeleteSuccessfull = "//div[contains(text(),'Returns deleted successfully')]"
Object_Federal_View = "//button[@aria-label='preview form details']"
Object_Federal_ViewSuccuess = "//button[@aria-label='close the popup']/preceding-sibling::div[contains(text(),'Form')]"
Object_StateInformationHeader = "//div[contains(text(),'Forms with state information')]"
Object_ContinueToFormDistribution = "//*[@id='ContinueToDistribution']"
Object_PrintEmail = "//p[@id='PrintMail']"
Object_OnlineAccess = "//p[@id='OnlineAccess']"
Object_PostalMailing = "//p[@id='Postalmailing']"
Object_BanditComplete = "//p[@id='BanditComplete']"
Object_ContinueToReviewForms = "//button[@aria-label='Continue to Review Forms']"
Object_ContinueToFormSumary = "//*[@id='ContinueToSummary']"
Object_ContinueToFormSumaryYes = "//button[@aria-label='No']"
Object_FilingSummaryHeader = "//h1[contains(text(),'Filing Summary')]"
Object_DeselectAll = "//span[contains(text(),'Deselect All ')]/parent::label"
Object_SelectAll = "//span[contains(text(),'Select All ')]/parent::label"
Object_AddFormForAnotherPayer = "//button[@class='v-btn v-btn--elevated v-theme--light bg-secondary v-btn--density-default v-btn--size-large v-btn--variant-elevated text-initial elevation-0']"
Object_TINMatching1099 = "//span[contains(text(),'1099 TIN Matching - ')]/parent::div/preceding-sibling::div/div/div/div/div/div/input[@id='tinmatching']"
Object_TINMatchingW2 = "//span[contains(text(),'1099 TIN Matching - ')]/parent::div/preceding-sibling::div/div/div/div/div/div/input[@id='tinmatching']"
Object_ProceedToCheckout = "//button[@id='ButtonText']"
Object_CompleteFiling = "//span[contains(text(),'Continue filing')]"
Object_CompleteYourOrder = "//span[text()='Complete Your Order ']"
Object_RemoveCreditApplied = "//span[contains(text(),'Credits Applied:')]/following-sibling::div/i"
Object_UseBanditCash = "//div[@id='usebanditcashlabel']"
Object_PaymentCreditCardHeader = "//div[contains(text(),'Review and Complete Your Order')]/parent::div/following-sibling::div/iframe"
Object_AgreeAndContinue = "//span[text()='Agree and Continue ']/parent::button"
#Object_AgreeAndContinue = "//label[@for='agreetoskip']"
Object_IAgreeToProceedWithThePayment = "//span[contains(text(),'I agree to proceed with the payment')]/parent::label"
Object_AcknowledgementContinue = "//span[contains(text(),'I agree to proceed with the payment')]/parent::label/parent::div/parent::div/parent::div/parent::div/following-sibling::button"
Object_SavedCard = "//div[contains(text(),'Saved Cards')]"
Object_SavedCardCVV = "//label[text()='CVV']/following-sibling::input"
Object_CreditCardNameOnCard = "//label[contains(text(),'Name on card')]/following-sibling::div/div/div/div/input"
Object_CreditCardCardNumberFrame = "//iframe[@title='secure payment field']"
Object_CreditCardCardNumber = "//input[@aria-label='Card number']"
Object_CreditCardExpirationDate = "//input[@placeholder='MM/YY']"
Object_CreditCardCVV = "//label[text()='CVV']/following-sibling::div/div/div/div[3]/input"
Object_CreditCardAcknowledgement = "//span[contains(text(),'I confirm that I have the authority to use this credit card and I authorize TaxBandits to charge my credit card.')]/parent::label"
Object_PayAndTransmit = "//span[text()='Pay and Transmit ']/parent::button"
Object_Congratulations = "//h1[contains(text(),'Your Order Completed Successfully.')]"
Object_OrderID = "//p[contains(text(),'Order ID')]/following-sibling::div"
Object_RecipientSummary="//span[text()='Continue to Recipient Summary']/parent::button"
Object_ContinueFiling="//span[text()=' Continue Filing ']/parent::button"