# Auto-generated locators from Team.xml

Object_ThreeDots = "//button[@aria-label='User Settings Menu']"
Object_NineDots = "//button[@aria-label='Control Panel']"
Object_BanditCollab = "//div[text()='BanditCollab ']"
Object_InviteTeam = "//span[text()=' Invite Team ']"
Object_AddIcon = "//button[@aria-label='Add']"
Object_Delete = "//button[@aria-label='Delete']"
Object_AssignPayer = "//*[text()='Assign Payers']"
Object_AddPayer = "//*[text()='Add Payer ']"
Object_AddPayerClose = "//button[@aria-label='Close pop up']"
Object_StartNew = "//*[text()=' Start Now '][1]"
Object_EIN = "//input[@id='textpayertin']"
Object_ReferenceNumber = "//input[@id='referencenumber']"
Object_PayerName = "//input[@id='payernametextfield']"
Object_DBA = "//input[@id='payertradename']"
Object_AddressLine1 = "//input[@id='payeraddressone']"
Object_AddressLine2 = "//input[@id='payeraddresstwo']"
Object_City = "//input[@id='payercityname']"
Object_State = "//input[@id='payerstatename']"
Object_SelectState = "//input[@value='NY']"
Object_ZIPCode = "//input[@id='payerzipcode']"
Object_FirstName = "//input[@id='payercontactfirstname']"
Object_MiddleInitial = "//input[@id='payercontactmiddlename']"
Object_LastName = "//input[@id='payercontactlastname']"
Object_Suffix = "//input[@id='payercontactsuffix']"
Object_SuffixSelect = "//input[@value='V']"
Object_EmailAddress = "//input[@id='payercontactemail']"
Object_PhoneNumber = "//input[@id='payercontactphonenumber']"
Object_AddpayerSave = "//button[@id='save']"
Object_USPSIgnoreAndContinue = "//*[text()=' Ignore and Continue']"
Object_AssignPayerClose = "//button[@aria-label='Close pop up']"
Object_TeamMemberName = "//input[@id='Entername_1']"
Object_Email = "//input[@id='Enteremail_1']"
Object_Role = "//input[@id='Selectrole1']"
Object_RolePreparer = "//span[text()='Preparer']"
Object_Group = "//input[@id='groupnametextfield1']"
Object_GroupSelect = "//div[@class='v-selection-control__input']/i"
Object_SaveAndContinue = "//span[text()=' Save and Continue ']"
Object_ManagePayer = "//div[@class='fs-14px text-black']/button/span[2]"
Object_Search = "//input[@id='search']"
Object_ClearSearch = "//i[@aria-label='Clear ']"
Object_BulkStartNow = "//button[@aria-label='To add bulk payer details']//span[text()=' Start Now ']"
Object_BulkBack = "//button[@aria-label='back']"
Object_PayerSelect = "//input[@aria-label='Selectlabel_0']"
Object_Assign = "//span[text()=' Assign ']"
