# Auto-generated locators from Youtube.xml

Object_NECYoutube = "//a[text()='How to file Form 1099-NEC?']"
Object_MISCYoutube = "//a[text()='How to file Form 1099-MISC?']"
Object_INTYoutube = "//a[text()='How to file Form 1099-INT?']"
Object_DIVYoutube = "//a[text()='How to file Form 1099-DIV?']"
Object_RYoutube = "//a[text()='How to file Form 1099-R?']"
Object_GYoutube = "//a[text()='How to file Form 1099-G?']"
Object_SYoutube = "//a[text()='How to file Form 1099-S?']"
Object_KYoutube = "//a[text()='How to file Form 1099-K?']"
Object_VerifyNEC = "//div[text()=' How to file Form 1099-NEC']"
Object_VerifyMISC = "//div[text()=' How to file Form 1099-MISC']"
Object_VerifyINT = "//div[text()=' How to file Form 1099-INT']"
Object_VerifyDIV = "//div[text()=' How to file Form 1099-DIV']"
Object_VerifyR = "//div[text()=' How to file Form 1099-R']"
Object_VerifyG = "//div[text()=' How to file Form 1099-G']"
Object_VerifyS = "//div[text()=' How to file Form 1099-S']"
Object_VerifyK = "//div[text()=' How to file Form 1099-K']"
Object_CloseNECYoutube = "//div[text()=' How to file Form 1099-NEC']/parent::div/button"
Object_CloseMISCYoutube = "//div[text()=' How to file Form 1099-MISV']/parent::div/button"
Object_CloseINTYoutube = "//div[text()=' How to file Form 1099-INT']/parent::div/button"
Object_CloseDIVYoutube = "//div[text()=' How to file Form 1099-DIV']/parent::div/button"
Object_CloseRYoutube = "//div[text()=' How to file Form 1099-R']/parent::div/button"
Object_CloseGYoutube = "//div[text()=' How to file Form 1099-G']/parent::div/button"
Object_CloseSYoutube = "//div[text()=' How to file Form 1099-S']/parent::div/button"
Object_CloseKYoutube = "//div[text()=' How to file Form 1099-K']/parent::div/button"
